name: Playwright Tests

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: # This allows you to manually trigger the workflow from the GitHub Actions interface. You can run the workflow on demand by clicking a button, which is useful for testing or when you want to run the tests outside of the scheduled times.

jobs: # This section defines the jobs that will be executed as part of the workflow. Each job represents a set of steps that will be run on a specific runner (virtual machine) provided by GitHub Actions. In this case, there is one job named "playwright" that will run the Playwright tests.
  playwright:
    timeout-minutes: 30 # This sets a timeout for the job, specifying that it should be automatically canceled if it runs for more than 30 minutes. This helps prevent long-running jobs from consuming resources indefinitely.
    runs-on: ubuntu-latest # Virtual machine(macos-latest, windows-latest, ubuntu-latest)

    # Setup the node js Version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
        # This action checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'


        # install dependencies
      - name: Install dependencies
        run: npm ci
        
       # install the playwright browsers
      - name: Install Playwright chroumium
        run: npx playwright install --with-deps chromium

        # Run the tests in headless mode(without a GUI)
        name: Run Playwright tests 
        run: npm run tests:headless


         # Upload the test result and reports
         name: Upload Playwright test results  # This step is responsible for uploading the test results and reports as artifacts to GitHub Actions. Artifacts are files generated during a workflow run that can be stored and accessed later. In this case, the test results and reports will be uploaded as artifacts, allowing you to review them even after the workflow has completed.
         uses: actions/upload-artifact@v3      # This action is used to upload artifacts to GitHub Actions. It takes care of the process of uploading files and making them available for download.
         
         if: always()  # This ensures that the artifact is uploaded even if the tests fail
         with: # This section specifies the details of the artifact to be uploaded.
           
           name: playwright-results
           path: |
                 test-results/  # This specifies the path to the test results that should be uploaded as artifacts. The "test-results/" directory is expected to contain the raw test results generated by the Playwright tests.
                 playwright-reports/  # This specifies the path to the test reports that should be uploaded as artifacts. The "playwright-reports/" directory is expected to contain the test results and reports generated by the Playwright tests.
           retention-days: 30  # This specifies how long the uploaded artifact should be retained in GitHub Actions. In this case, the artifact will be kept for 7 days before it is automatically deleted. This allows you to access the test results and reports for a reasonable period of time after the workflow has completed.             
            

      -
